eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=api-gateway:8080
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

spring.cloud.gateway.server.webflux.routes[0].id=pos-application-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://pos-application
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/pos/**

spring.cloud.gateway.server.webflux.httpclient.connect-timeout=5000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=30s

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
