# North-East routing
app.routing.state-code-header=X-State-Code
app.routing.default-state-code=AS
app.routing.allowed-state-codes=AS,AR,ML,MN,MZ,NL,TR

# Common physical database connection
# All state datasources use this database with different schemas.
pos.ne.jdbc-base=jdbc:postgresql://10.246.45.14:5432/mFMS
pos.ne.username=pos_ne_user

# Assam
app.state-databases.AS.jdbc-url=${pos.ne.jdbc-base}?currentSchema=mfms
app.state-databases.AS.username=harekrishna
app.state-databases.AS.password=Harekrishna@nic
app.state-databases.AS.driver-class-name=org.postgresql.Driver
app.state-databases.AS.minimum-idle=1
app.state-databases.AS.maximum-pool-size=5

# Arunachal Pradesh
app.state-databases.AR.jdbc-url=${pos.ne.jdbc-base}?currentSchema=mfms
app.state-databases.AR.username=harekrishna
app.state-databases.AR.password=Harekrishna@nic
app.state-databases.AR.driver-class-name=org.postgresql.Driver
app.state-databases.AR.minimum-idle=1
app.state-databases.AR.maximum-pool-size=5

# Meghalaya
app.state-databases.ML.jdbc-url=${pos.ne.jdbc-base}?currentSchema=mfms
app.state-databases.ML.username=harekrishna
app.state-databases.ML.password=Harekrishna@nic
app.state-databases.ML.driver-class-name=org.postgresql.Driver
app.state-databases.ML.minimum-idle=1
app.state-databases.ML.maximum-pool-size=5

# Manipur
app.state-databases.MN.jdbc-url=${pos.ne.jdbc-base}?currentSchema=mfms
app.state-databases.MN.username=harekrishna
app.state-databases.MN.password=Harekrishna@nic
app.state-databases.MN.driver-class-name=org.postgresql.Driver
app.state-databases.MN.minimum-idle=1
app.state-databases.MN.maximum-pool-size=5

# Mizoram
app.state-databases.MZ.jdbc-url=${pos.ne.jdbc-base}?currentSchema=mfms
app.state-databases.MZ.username=harekrishna
app.state-databases.MZ.password=Harekrishna@nic
app.state-databases.MZ.driver-class-name=org.postgresql.Driver
app.state-databases.MZ.minimum-idle=1
app.state-databases.MZ.maximum-pool-size=5

# Nagaland
app.state-databases.NL.jdbc-url=${pos.ne.jdbc-base}?currentSchema=mfms
app.state-databases.NL.username=harekrishna
app.state-databases.NL.password=Harekrishna@nic
app.state-databases.NL.driver-class-name=org.postgresql.Driver
app.state-databases.NL.minimum-idle=1
app.state-databases.NL.maximum-pool-size=5

# Tripura
app.state-databases.TR.jdbc-url=${pos.ne.jdbc-base}?currentSchema=mfms
app.state-databases.TR.username=harekrishna
app.state-databases.TR.password=Harekrishna@nic
app.state-databases.TR.driver-class-name=org.postgresql.Driver
app.state-databases.TR.minimum-idle=1
app.state-databases.TR.maximum-pool-size=5


# Log file
logging.file.name=/opt/ifms-pos/logs/pos-ne.log
