pos.state.id=9
pos.state.code=UP
pos.state.name=Uttar Pradesh
pos.state.schema=mfms_UP

spring.datasource.url=jdbc:postgresql://10.247.222.10:5432/mFMSUP?currentSchema=mfms_UP
spring.datasource.username=pos_up_user
spring.datasource.password=${POS_DB_PASSWORD}

spring.datasource.hikari.pool-name=POS-UP-HikariPool
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=50

spring.datasource.hikari.data-source-properties.ApplicationName=IFMS-POS-UP
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true
spring.datasource.hikari.data-source-properties.tcpKeepAlive=true
spring.datasource.hikari.data-source-properties.connectTimeout=30
spring.datasource.hikari.data-source-properties.socketTimeout=300

logging.file.name=/opt/ifms-pos/logs/pos-up.log
