pos.state.id=27
pos.state.code=MH
pos.state.name=Maharastra
pos.state.schema=mfms_mh

spring.datasource.url=jdbc:postgresql://10.247.222.10:5432/mFMSUP?currentSchema=mfms_mh
spring.datasource.username=pos_mh_user
spring.datasource.password=${POS_DB_PASSWORD}

spring.datasource.hikari.pool-name=POS-MH-HikariPool
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=50

spring.datasource.hikari.data-source-properties.ApplicationName=IFMS-POS-UP
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true
spring.datasource.hikari.data-source-properties.tcpKeepAlive=true
spring.datasource.hikari.data-source-properties.connectTimeout=30
spring.datasource.hikari.data-source-properties.socketTimeout=300

logging.file.name=/opt/ifms-pos/logs/pos-up.log
